### ISSUE TITLE
Problema para tejer imagenes

### ISSUE THREAD

**Issue by masuero** [maestria-geotel-201902/unidad-1-asignacion-1-datos-espaciales-en-r-masuero#1]
Hola!! Tengo problemas para que se tejan las imágenes. En el preview que me da Rstudio cuando tejo, se genera el markdown pero sin imágenes. No veo el archivo de las imágenes para hacer el push. Pero ellas se generaron cuando fui ejecutando los códigos. 

![image](https://user-images.githubusercontent.com/39682213/67728632-3fc08a80-f9c4-11e9-9916-8b87e0656ddc.png)

**Comment by geofis** [comment]
Lo más probable es que no cambiaste la opción del encabezado `eval`. Está puesto como `eval=F` pero debes cambiarlo a `eval=T`. Lo pone el archivo al inicio:

> Dentro de las opciones de `knitr`, en el encabezado de este archivo, es probable que encuentres el argumento `eval = F`. Antes de tejer debes cambiarlo a `eval = T`, para que evalúe los bloques de código según tus cambios

Cambia dicha opción, teje de nuevo y verás que sí funciona.

**Comment by masuero** [comment]
Hola Tali,
Efectivamente tenía la letra equivocada (lo que me sirvió para que me aprendiera que es una función de evaluar y que le digo "False" o "True"), sin embargo me esta ocurriendo lo mismo que a Diego, se me teje el markdown con las imágenes pero no me aparecen el en Git. Vi la solución que le dio a el pero parece que yo hice push de manera equivocada. 
Al principio en esta imagen me aparecían los archivos de la imagen y del Rproj, pero ahora tejo y me aparecen pero luego rápidamente se quitan.

![image](https://user-images.githubusercontent.com/39682213/67729898-6df49900-f9c9-11e9-9ff8-457aa1588ef9.png)

**Comment by geofis** [comment]
El tali de este lado.

Las imágenes ya subieron, pero todavía no has subido el `.Rmd` ni el `.md`. Por tal razón, si vas a tu [repo en GitHub](https://github.com/maestria-geotel-201902/unidad-1-asignacion-1-datos-espaciales-en-r-masuero) verás que la carpeta imágenes existe y tiene los archivos allí (hiciste *commit*>*push* de ellas), pero los archivos `.Rmd` y `.md` son antiguos. Tienes que hacer *commit*>*push* a estos dos archivos también.

**Comment by masuero** [comment]
Gracias Tali por la ayuda. Ya pude subir el markdown con las imagenes.

**Comment by geofis** [comment]
Perfecto.
